insert into client (name, surname, email, date_of_birth, phone) values ('Rycca', 'Bras', 'rbras0@google.com.au', '1971-05-04', '5281550064');
insert into client (name, surname, email, date_of_birth, phone) values ('Case', 'Torricina', 'ctorricina1@canalblog.com', '1948-12-21', '8673482992');
insert into client (name, surname, email, date_of_birth, phone) values ('Nadeen', 'Chalice', 'nchalice2@va.gov', '1944-10-17', '2774892967');
insert into client (name, surname, email, date_of_birth, phone) values ('Mitchell', 'Whittall', 'mwhittall3@acquirethisname.com', '1968-05-29', '3918938236');
insert into client (name, surname, email, date_of_birth, phone) values ('Bryon', 'Lewnden', 'blewnden4@bbc.co.uk', '1960-03-18', '8624249506');
insert into client (name, surname, email, date_of_birth, phone) values ('Kare', 'Birdall', 'kbirdall5@ebay.co.uk', '1987-11-18', '8793669981');
insert into client (name, surname, email, date_of_birth, phone) values ('Guthry', 'Patrick', 'gpatrick6@ted.com', '1968-07-14', '7966153797');
insert into client (name, surname, email, date_of_birth, phone) values ('Nissy', 'McCanny', 'nmccanny7@histats.com', '1975-08-18', '6108653605');
insert into client (name, surname, email, date_of_birth, phone) values ('Mindy', 'Morsom', 'mmorsom8@samsung.com', '1990-11-26', '1683367617');
insert into client (name, surname, email, date_of_birth, phone) values ('Ronnie', 'Whetton', 'rwhetton9@cornell.edu', '1984-06-02', '3382587098');
insert into client (name, surname, email, date_of_birth, phone) values ('Roxie', 'Jane', 'rjanea@arizona.edu', '1980-03-15', '4144783109');
insert into client (name, surname, email, date_of_birth, phone) values ('Silva', 'Montes', 'smontesb@cornell.edu', '2000-01-23', '1991020245');
insert into client (name, surname, email, date_of_birth, phone) values ('Odella', 'Dufty', 'oduftyc@geocities.jp', '1941-04-04', '7556178977');
insert into client (name, surname, email, date_of_birth, phone) values ('Caron', 'Voak', 'cvoakd@de.vu', '1993-07-02', '4437934051');
insert into client (name, surname, email, date_of_birth, phone) values ('Turner', 'Grishinov', 'tgrishinove@xing.com', '1942-04-22', '6207365982');
insert into client (name, surname, email, date_of_birth, phone) values ('Verena', 'Gavan', 'vgavanf@slate.com', '1945-04-02', '6604519831');
insert into client (name, surname, email, date_of_birth, phone) values ('Adrea', 'Dignam', 'adignamg@timesonline.co.uk', '1960-05-17', '4625235284');
insert into client (name, surname, email, date_of_birth, phone) values ('Hurleigh', 'Aggiss', 'haggissh@google.it', '1953-02-21', '4884570757');
insert into client (name, surname, email, date_of_birth, phone) values ('Brenden', 'Barabich', 'bbarabichi@booking.com', '1990-01-22', '5234779746');
insert into client (name, surname, email, date_of_birth, phone) values ('Valery', 'McRobert', 'vmcrobertj@fastcompany.com', '1946-02-06', '1736615077');

insert into product (product_name, margin, unit_price) values ('Horseradish - Prepared', 1.8, 7.6);
insert into product (product_name, margin, unit_price) values ('Pepper - Scotch Bonnet', 2.22, 37.03);
insert into product (product_name, margin, unit_price) values ('Garbage Bags - Clear', 5.97, 1.57);
insert into product (product_name, margin, unit_price) values ('Pastry - Apple Large', 3.11, 2.38);
insert into product (product_name, margin, unit_price) values ('Soho Lychee Liqueur', 2.39, 46.74);
insert into product (product_name, margin, unit_price) values ('Squash - Acorn', 2.25, 30.48);
insert into product (product_name, margin, unit_price) values ('Steampan - Foil', 6.86, 31.63);
insert into product (product_name, margin, unit_price) values ('Jam - Apricot', 4.17, 18.32);
insert into product (product_name, margin, unit_price) values ('True - Vue Containers', 8.83, 33.59);
insert into product (product_name, margin, unit_price) values ('Wine - Chateauneuf Du Pape', 9.15, 16.5);
insert into product (product_name, margin, unit_price) values ('Parsnip', 8.6, 27.57);
insert into product (product_name, margin, unit_price) values ('Aromat Spice / Seasoning', 9.72, 39.76);
insert into product (product_name, margin, unit_price) values ('Watercress', 7.93, 42.57);
insert into product (product_name, margin, unit_price) values ('Ketchup - Tomato', 9.35, 22.0);
insert into product (product_name, margin, unit_price) values ('Drambuie', 6.9, 47.82);
insert into product (product_name, margin, unit_price) values ('Longos - Chicken Wings', 8.03, 36.25);
insert into product (product_name, margin, unit_price) values ('Flower - Daisies', 8.36, 12.34);
insert into product (product_name, margin, unit_price) values ('Sauce - Caesar Dressing', 2.04, 34.7);
insert into product (product_name, margin, unit_price) values ('Syrup - Monin, Irish Cream', 1.45, 44.69);
insert into product (product_name, margin, unit_price) values ('Lamb - Bones', 2.0, 39.72);
insert into product (product_name, margin, unit_price) values ('Bread - Dark Rye', 4.42, 18.66);
insert into product (product_name, margin, unit_price) values ('Sole - Fillet', 7.91, 37.51);
insert into product (product_name, margin, unit_price) values ('Coffee - Espresso', 6.0, 15.09);
insert into product (product_name, margin, unit_price) values ('Wine - Two Oceans Cabernet', 8.49, 16.86);
insert into product (product_name, margin, unit_price) values ('Wine - Chablis 2003 Champs', 5.47, 40.28);
insert into product (product_name, margin, unit_price) values ('Pate - Liver', 7.22, 45.97);
insert into product (product_name, margin, unit_price) values ('Versatainer Nc - 888', 7.96, 9.24);
insert into product (product_name, margin, unit_price) values ('Shrimp - 16/20, Iqf, Shell On', 1.69, 48.93);
insert into product (product_name, margin, unit_price) values ('Table Cloth 120 Round White', 5.73, 46.64);
insert into product (product_name, margin, unit_price) values ('Quail - Eggs, Fresh', 9.90, 6.94);
insert into product (product_name, margin, unit_price) values ('Potatoes - Mini White 3 Oz', 7.0, 33.91);
insert into product (product_name, margin, unit_price) values ('Cookie Dough - Double', 7.62, 47.95);
insert into product (product_name, margin, unit_price) values ('Flower - Commercial Spider', 9.17, 21.72);
insert into product (product_name, margin, unit_price) values ('Grand Marnier', 8.95, 4.45);
insert into product (product_name, margin, unit_price) values ('Wine - Alsace Riesling Reserve', 3.5, 15.8);
insert into product (product_name, margin, unit_price) values ('Baking Powder', 9.84, 27.08);
insert into product (product_name, margin, unit_price) values ('Chocolate - Milk', 9.02, 44.86);
insert into product (product_name, margin, unit_price) values ('Cake - Sheet Strawberry', 8.3, 25.27);
insert into product (product_name, margin, unit_price) values ('Chocolate - White', 1.16, 26.41);
insert into product (product_name, margin, unit_price) values ('Tea - Green', 8.72, 11.28);
insert into product (product_name, margin, unit_price) values ('Bread - Onion Focaccia', 8.44, 30.58);
insert into product (product_name, margin, unit_price) values ('Green Tea Refresher', 3.56, 21.26);
insert into product (product_name, margin, unit_price) values ('Cocoa Powder - Natural', 8.75, 40.66);
insert into product (product_name, margin, unit_price) values ('Huck White Towels', 7.23, 6.3);
insert into product (product_name, margin, unit_price) values ('Pork - Ground', 6.11, 5.21);
insert into product (product_name, margin, unit_price) values ('Wine - Rubyport', 5.14, 46.72);
insert into product (product_name, margin, unit_price) values ('Muffin Orange Individual', 8.57, 4.72);
insert into product (product_name, margin, unit_price) values ('Bag - Clear 7 Lb', 1.91, 29.23);
insert into product (product_name, margin, unit_price) values ('Pasta - Rotini, Dry', 3.62, 36.88);
insert into product (product_name, margin, unit_price) values ('Wine - Baron De Rothschild', 8.34, 1.41);

insert into transaction (order_date, status, client_id) values ('2016-05-24', 'IN_ORDER', 5);
insert into transaction (order_date, status, client_id) values ('2017-04-08', 'WAITING_FOR_PAYMENT', 18);
insert into transaction (order_date, status, client_id) values ('2016-01-31', 'CANCELLED', 11);
insert into transaction (order_date, status, client_id) values ('2016-11-18', 'CANCELLED', 3);
insert into transaction (order_date, status, client_id) values ('2017-10-09', 'PROCESSED', 6);
insert into transaction (order_date, status, client_id) values ('2016-02-05', 'PROCESSING', 9);
insert into transaction (order_date, status, client_id) values ('2016-03-08', 'IN_ORDER', 17);
insert into transaction (order_date, status, client_id) values ('2016-09-28', 'PROCESSED', 12);
insert into transaction (order_date, status, client_id) values ('2017-04-03', 'CANCELLED', 16);
insert into transaction (order_date, status, client_id) values ('2017-07-19', 'CANCELLED', 6);
insert into transaction (order_date, status, client_id) values ('2016-11-03', 'WAITING_FOR_PAYMENT', 17);
insert into transaction (order_date, status, client_id) values ('2016-07-25', 'PROCESSING', 1);
insert into transaction (order_date, status, client_id) values ('2017-03-05', 'PROCESSING', 6);
insert into transaction (order_date, status, client_id) values ('2016-08-08', 'PROCESSED', 12);
insert into transaction (order_date, status, client_id) values ('2016-04-30', 'PROCESSED', 3);
insert into transaction (order_date, status, client_id) values ('2017-09-05', 'WAITING_FOR_PAYMENT', 16);
insert into transaction (order_date, status, client_id) values ('2016-03-03', 'PROCESSED', 10);
insert into transaction (order_date, status, client_id) values ('2017-06-19', 'CANCELLED', 10);
insert into transaction (order_date, status, client_id) values ('2016-10-16', 'IN_ORDER', 4);
insert into transaction (order_date, status, client_id) values ('2016-07-07', 'CANCELLED', 19);
insert into transaction (order_date, status, client_id) values ('2017-06-05', 'PROCESSED', 4);
insert into transaction (order_date, status, client_id) values ('2016-04-05', 'PROCESSED', 4);
insert into transaction (order_date, status, client_id) values ('2016-08-06', 'IN_ORDER', 16);
insert into transaction (order_date, status, client_id) values ('2016-03-28', 'WAITING_FOR_PAYMENT', 18);
insert into transaction (order_date, status, client_id) values ('2016-03-13', 'PROCESSING', 4);
insert into transaction (order_date, status, client_id) values ('2016-08-13', 'PROCESSED', 5);
insert into transaction (order_date, status, client_id) values ('2017-09-16', 'PROCESSING', 11);
insert into transaction (order_date, status, client_id) values ('2016-08-01', 'WAITING_FOR_PAYMENT', 19);
insert into transaction (order_date, status, client_id) values ('2017-07-05', 'CANCELLED', 4);
insert into transaction (order_date, status, client_id) values ('2017-06-26', 'WAITING_FOR_PAYMENT', 10);
insert into transaction (order_date, status, client_id) values ('2017-07-18', 'PROCESSED', 20);
insert into transaction (order_date, status, client_id) values ('2017-10-23', 'CANCELLED', 6);
insert into transaction (order_date, status, client_id) values ('2017-07-24', 'CANCELLED', 17);
insert into transaction (order_date, status, client_id) values ('2017-05-13', 'CANCELLED', 10);
insert into transaction (order_date, status, client_id) values ('2016-06-11', 'IN_ORDER', 16);
insert into transaction (order_date, status, client_id) values ('2016-09-20', 'WAITING_FOR_PAYMENT', 8);
insert into transaction (order_date, status, client_id) values ('2017-05-26', 'IN_ORDER', 2);
insert into transaction (order_date, status, client_id) values ('2017-02-26', 'WAITING_FOR_PAYMENT', 14);
insert into transaction (order_date, status, client_id) values ('2017-06-14', 'PROCESSING', 1);
insert into transaction (order_date, status, client_id) values ('2016-10-30', 'CANCELLED', 18);
insert into transaction (order_date, status, client_id) values ('2017-09-17', 'WAITING_FOR_PAYMENT', 17);
insert into transaction (order_date, status, client_id) values ('2017-02-01', 'PROCESSED', 7);
insert into transaction (order_date, status, client_id) values ('2016-06-05', 'CANCELLED', 11);
insert into transaction (order_date, status, client_id) values ('2017-01-23', 'PROCESSED', 7);
insert into transaction (order_date, status, client_id) values ('2017-01-15', 'PROCESSING', 20);
insert into transaction (order_date, status, client_id) values ('2017-04-06', 'CANCELLED', 11);
insert into transaction (order_date, status, client_id) values ('2016-04-03', 'PROCESSED', 17);
insert into transaction (order_date, status, client_id) values ('2016-08-27', 'PROCESSED', 6);
insert into transaction (order_date, status, client_id) values ('2017-09-15', 'PROCESSED', 8);
insert into transaction (order_date, status, client_id) values ('2016-12-16', 'PROCESSED', 15);
insert into transaction (order_date, status, client_id) values ('2016-07-07', 'PROCESSING', 9);
insert into transaction (order_date, status, client_id) values ('2016-06-18', 'IN_ORDER', 19);
insert into transaction (order_date, status, client_id) values ('2017-01-19', 'CANCELLED', 5);
insert into transaction (order_date, status, client_id) values ('2017-05-11', 'PROCESSED', 11);
insert into transaction (order_date, status, client_id) values ('2017-03-08', 'CANCELLED', 1);
insert into transaction (order_date, status, client_id) values ('2017-01-06', 'IN_ORDER', 2);
insert into transaction (order_date, status, client_id) values ('2017-11-20', 'CANCELLED', 19);
insert into transaction (order_date, status, client_id) values ('2017-04-24', 'PROCESSED', 12);
insert into transaction (order_date, status, client_id) values ('2017-02-13', 'CANCELLED', 18);
insert into transaction (order_date, status, client_id) values ('2016-12-03', 'CANCELLED', 8);
insert into transaction (order_date, status, client_id) values ('2016-12-01', 'WAITING_FOR_PAYMENT', 10);
insert into transaction (order_date, status, client_id) values ('2016-01-15', 'CANCELLED', 6);
insert into transaction (order_date, status, client_id) values ('2016-03-27', 'PROCESSED', 4);
insert into transaction (order_date, status, client_id) values ('2016-12-31', 'CANCELLED', 8);
insert into transaction (order_date, status, client_id) values ('2016-09-26', 'IN_ORDER', 11);
insert into transaction (order_date, status, client_id) values ('2016-03-29', 'WAITING_FOR_PAYMENT', 16);
insert into transaction (order_date, status, client_id) values ('2016-02-28', 'CANCELLED', 15);
insert into transaction (order_date, status, client_id) values ('2017-09-18', 'PROCESSING', 19);
insert into transaction (order_date, status, client_id) values ('2016-11-10', 'WAITING_FOR_PAYMENT', 3);
insert into transaction (order_date, status, client_id) values ('2016-07-01', 'PROCESSED', 20);
insert into transaction (order_date, status, client_id) values ('2017-02-22', 'PROCESSING', 15);
insert into transaction (order_date, status, client_id) values ('2016-11-29', 'PROCESSED', 4);
insert into transaction (order_date, status, client_id) values ('2017-10-20', 'IN_ORDER', 2);
insert into transaction (order_date, status, client_id) values ('2016-07-31', 'WAITING_FOR_PAYMENT', 14);
insert into transaction (order_date, status, client_id) values ('2016-03-01', 'CANCELLED', 10);
insert into transaction (order_date, status, client_id) values ('2016-05-06', 'PROCESSING', 9);
insert into transaction (order_date, status, client_id) values ('2016-02-13', 'PROCESSING', 19);
insert into transaction (order_date, status, client_id) values ('2017-05-24', 'IN_ORDER', 10);
insert into transaction (order_date, status, client_id) values ('2016-09-07', 'CANCELLED', 4);
insert into transaction (order_date, status, client_id) values ('2016-05-10', 'CANCELLED', 9);
insert into transaction (order_date, status, client_id) values ('2016-03-07', 'IN_ORDER', 20);
insert into transaction (order_date, status, client_id) values ('2016-05-06', 'IN_ORDER', 8);
insert into transaction (order_date, status, client_id) values ('2017-10-10', 'WAITING_FOR_PAYMENT', 13);
insert into transaction (order_date, status, client_id) values ('2016-03-31', 'PROCESSED', 4);
insert into transaction (order_date, status, client_id) values ('2017-02-17', 'PROCESSING', 12);
insert into transaction (order_date, status, client_id) values ('2017-01-03', 'PROCESSED', 16);
insert into transaction (order_date, status, client_id) values ('2017-06-19', 'WAITING_FOR_PAYMENT', 7);
insert into transaction (order_date, status, client_id) values ('2016-03-25', 'PROCESSED', 5);
insert into transaction (order_date, status, client_id) values ('2017-02-23', 'CANCELLED', 7);
insert into transaction (order_date, status, client_id) values ('2017-05-16', 'PROCESSING', 5);
insert into transaction (order_date, status, client_id) values ('2016-03-03', 'CANCELLED', 13);
insert into transaction (order_date, status, client_id) values ('2017-09-15', 'WAITING_FOR_PAYMENT', 11);
insert into transaction (order_date, status, client_id) values ('2016-09-30', 'WAITING_FOR_PAYMENT', 19);
insert into transaction (order_date, status, client_id) values ('2017-03-12', 'PROCESSING', 7);
insert into transaction (order_date, status, client_id) values ('2016-05-04', 'PROCESSED', 7);
insert into transaction (order_date, status, client_id) values ('2017-04-11', 'WAITING_FOR_PAYMENT', 5);
insert into transaction (order_date, status, client_id) values ('2016-08-02', 'WAITING_FOR_PAYMENT', 1);
insert into transaction (order_date, status, client_id) values ('2017-04-06', 'IN_ORDER', 2);
insert into transaction (order_date, status, client_id) values ('2016-11-13', 'WAITING_FOR_PAYMENT', 17);
insert into transaction (order_date, status, client_id) values ('2016-05-02', 'PROCESSING', 4);


insert into product_list (number_of_items, transaction_id, product_id) values (7, 52, 46);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 45, 7);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 45, 5);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 81, 31);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 96, 8);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 79, 7);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 55, 4);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 64, 7);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 67, 40);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 22, 9);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 18, 41);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 75, 35);
insert into product_list (number_of_items, transaction_id, product_id) values (3, 18, 39);
insert into product_list (number_of_items, transaction_id, product_id) values (3, 85, 21);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 50, 25);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 40, 31);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 57, 31);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 39, 20);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 86, 41);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 93, 10);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 89, 27);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 59, 38);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 37, 41);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 87, 41);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 80, 47);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 85, 50);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 88, 22);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 32, 12);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 21, 11);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 72, 7);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 88, 4);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 70, 9);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 78, 45);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 7, 13);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 50, 2);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 96, 37);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 69, 42);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 85, 39);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 2, 16);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 21, 14);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 34, 48);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 95, 10);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 27, 14);
insert into product_list (number_of_items, transaction_id, product_id) values (3, 65, 2);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 52, 18);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 17, 47);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 85, 42);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 81, 33);
insert into product_list (number_of_items, transaction_id, product_id) values (3, 28, 48);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 43, 19);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 42, 11);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 86, 12);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 6, 20);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 21, 13);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 85, 3);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 76, 12);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 93, 22);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 66, 41);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 24, 3);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 49, 11);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 92, 49);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 53, 19);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 7, 12);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 44, 29);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 48, 30);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 30, 27);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 46, 16);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 72, 1);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 37, 41);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 40, 30);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 78, 8);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 32, 42);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 8, 5);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 50, 1);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 82, 33);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 26, 38);
insert into product_list (number_of_items, transaction_id, product_id) values (3, 36, 22);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 82, 5);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 58, 5);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 33, 50);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 53, 38);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 71, 9);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 87, 3);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 29, 42);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 38, 28);
insert into product_list (number_of_items, transaction_id, product_id) values (3, 77, 13);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 61, 31);
insert into product_list (number_of_items, transaction_id, product_id) values (9, 4, 42);
insert into product_list (number_of_items, transaction_id, product_id) values (6, 84, 19);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 60, 10);
insert into product_list (number_of_items, transaction_id, product_id) values (10, 13, 37);
insert into product_list (number_of_items, transaction_id, product_id) values (2, 22, 49);
insert into product_list (number_of_items, transaction_id, product_id) values (1, 37, 15);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 74, 49);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 41, 37);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 100, 42);
insert into product_list (number_of_items, transaction_id, product_id) values (8, 100, 17);
insert into product_list (number_of_items, transaction_id, product_id) values (7, 61, 30);
insert into product_list (number_of_items, transaction_id, product_id) values (4, 78, 25);
insert into product_list (number_of_items, transaction_id, product_id) values (5, 32, 20);



